//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fakturisanje.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FaktureDBEntities : DbContext
    {
        public FaktureDBEntities()
            : base("name=FaktureDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FakturaTable> FakturaTables { get; set; }
        public virtual DbSet<StavkaFaktureTable> StavkaFaktureTables { get; set; }

        internal void ApplyPropertyChanges(object entitySetName)
        {
            throw new NotImplementedException();
        }

        internal void ApplyPropertyChanges(object entitySetName, FakturaTable fakturaEdit)
        {
            throw new NotImplementedException();
        }

        internal object ExecuteStoreQuery<T>(string sql, object[] myParams)
        {
            throw new NotImplementedException();
        }
    }
}
