//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fakturisanje.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class FakturaTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FakturaTable()
        {
            this.StavkaFaktureTables = new List<StavkaFaktureTable>();
        }


        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int fakturaID { get; set; }
        //public Nullable<System.DateTime> datum_fakture { get; set; }

        [DisplayName("Datum fakture")]
        public Nullable<System.DateTime> datum_fakture { get; set; }
        
        //public DateTime? datum_fakture { get; set; }

        [DisplayName("Broj fakture")]
        public Nullable<int> broj_fakture { get; set; }

        [DisplayName("Ukupno")]
        public Nullable<decimal> ukupno { get; set; }

        [DisplayName("Datum dokumenta")]
        public System.DateTime datum_dokumenta { get; set; }

        [DisplayName("Broj dokumenta")]
        public string broj_dokumenta { get; set; }

        [DisplayName("Uk broj stavki")]
        public Nullable<int> ukupno_stavki { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<StavkaFaktureTable> StavkaFaktureTables { get; set; }
        public object EntityKey { get; internal set; }

        public string ReturnDatumFaktureForDisplay
        {
            get
            {
                return ((DateTime)this.datum_fakture).ToString("dd.MM.yyyy");

            }
        }

        public string ReturnDatumDokumentaForDisplay
        {
            get
            {
                return ((DateTime)this.datum_dokumenta).ToString("dd.MM.yyyy");

            }
        }
        
    }
}
