//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fakturisanje.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class StavkaFaktureTable
    {
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        [DisplayName("Redni broj")]
        public int redniBr { get; set; }

        [DisplayName("Faktura ID")]
        public int fakturaID { get; set; }

        [DisplayName("Kolicina")]
        public int kolicina { get; set; }

        [DisplayName("Cena")]
        public Nullable<decimal> cena { get; set; }

        [DisplayName("Ukupno")]
        public Nullable<decimal> ukupno { get; set; }
    
        public virtual FakturaTable FakturaTable { get; set; }
    }
}
